### PR TITLE
Add changelog entries for 2.0.0 and 2.0.1

### PR DESCRIPTION
**Pull request by GlenWalker**
Here's my best guess changelog entry for 2.0.0, and a 2.0.1 entry for #25 (which I'm hoping can be released to PyPI soon)

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
lovely, thanks!

**Comment by GlenWalker** [comment]
Cool. What do we need to do to get this released?

**Comment by GlenWalker** [comment]
Oh, I see 2.0.1 just popped up on PyPI a few minutes ago, so thanks! I don't own any packages on PyPI, and so have no idea how that process works.

**Comment by RonnyPfannschmidt** [comment]
@GlenWalker we have a deploy bit in github workflows, so its literally jist declaring a release on github, and a few minutes later its published

**Pull request merged**
